### ISSUE TITLE
Possible to shopt -s expand_aliases when used?  OK?

### ISSUE THREAD

**Issue by JPHutchins** [JPHutchins/envr#22]
GitHub workflows don't have this enabled in their shells.  Would it be OK to set this when envr is sourced so that workflows do not have to treat sh as a special case?

```yaml
      - name: Test (Linux or MacOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          shopt -s expand_aliases
          . ./envr.ps1
          test
      
      - name: Test (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          .\envr.ps1
          test
  ```
